config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :elists

  resources :contacts

  resources :pros do
      resources :services, :photos
  end

  get 'pages/home'

  get 'InfoForExperts', :to => 'pages#info', :as => :info
  get 'Mission', :to => 'pages#mission', :as => :mission
  get 'About', :to => 'pages#about', :as => :about
  get 'Privacy', :to => 'pages#privacy', :as => :privacy
  get 'Terms', :to => 'pages#terms', :as => :terms

  get 'pros/profile'

  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/elist.rb
class Elist < ActiveRecord::Base

	  validates  :name, :email, :city, presence: true
end

app/controllers/elists_controller.rb
class ElistsController < ApplicationController
  before_action :set_elist, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @elists = Elist.all
    respond_with(@elists)
  end

  def show
    respond_with(@elist)
  end

  def new
    @elist = Elist.new

  end

  def edit
  end

  def create
    @elist = Elist.new(elist_params)

      respond_to do |format|
      if @elist.save
        format.html { redirect_to root_path, alert: 'Thank you for joining the wait list!' }
        format.json { render :show, status: :created, location: @contact}
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end    
  end

  def update
    @elist.update(elist_params)
    respond_with(@elist)
  end

  def destroy
    @elist.destroy
    respond_with(@elist)
  end

  private
    def set_elist
      @elist = Elist.find(params[:id])
    end

    def elist_params
      params.require(:elist).permit(:name, :email, :city)
    end
end

app/helpers/elists_helper.rb
module ElistsHelper
end

app/views/elists/_form.html.erb
<%= simple_form_for(@elist, :class => "form-control") do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Your name*", label: '&nbsp;'.html_safe  %>
    <%= f.input :email, placeholder: "Your email*", label: '&nbsp;'.html_safe  %>

    <%= f.input :city, input_html: {id: "locality"}, placeholder: "Your city*", label: '&nbsp;'.html_safe  %>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>
  </div>

	<br>
	<div class="form-actions">
    	<%= f.submit "Submit", class: 'f_bold btn btn-default btn-theme btn-lg' %>
    </div>

<% end %>

<%= render "users/script_city_autocomplete" %>

app/views/elists/_hform.html.erb

<%= simple_form_for(@elist, :class => "form-control") do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group col-md-6">
    <%= f.input :name, placeholder: "Your name*", label: false %>
    </div>

    <div class="form-group col-md-6">
    <%= f.input :email, placeholder: "Your email*", label: false %>
    </div>

    <div class="form-group col-sm-12">
    <%= f.input :city, input_html: {id: "locality"}, placeholder: "Your city*", label: false %>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>
    </div>    
  </div>

	<br>
  <div class="form-group col-sm-12">
	<div class="form-actions">
    	<%= f.submit "Let's Go!", class: 'btn btn-default btn-block' %>
    </div>
</div>

<% end %>

<%= render "users/script_city_autocomplete" %>

app/views/elists/edit.html.erb
<h1>Editing elist</h1>

<%= render 'form' %>

<%= link_to 'Show', @elist %> |
<%= link_to 'Back', elists_path %>

app/views/elists/index.html.erb
<h1>Listing elists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elists.each do |elist| %>
      <tr>
        <td><%= elist.name %></td>
        <td><%= elist.email %></td>
        <td><%= elist.city %></td>
        <td><%= link_to 'Show', elist %></td>
        <td><%= link_to 'Edit', edit_elist_path(elist) %></td>
        <td><%= link_to 'Destroy', elist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elist', new_elist_path %>

app/views/elists/new.html.erb
<section class="upcoming-evets">
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="base-container">
              <div class="section-title">
                <ul class="list-inline">
                  <li class="base-title">Join our mailing list</li>
                </ul>
              </div> 


<div class="row">   
	<div class="col-sm-6 col-md-4">
		<br>		
		<p>GoodLooks will be rolling out our suite of experts shortly!  Be the first to be notified</p>

	</div>

<div class="col-sm-6 col-md-4 col-md-offset-1">
<%= render 'form' %>
</div>



</div>
</div>
</div>
</div>
</section>

app/views/elists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @elist.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @elist.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @elist.city %>
</p>

<%= link_to 'Edit', edit_elist_path(@elist) %> |
<%= link_to 'Back', elists_path %>