config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :elists

  resources :contacts

  resources :pros do
      resources :services, :photos
  end

  get 'pages/home'

  get 'InfoForExperts', :to => 'pages#info', :as => :info
  get 'Mission', :to => 'pages#mission', :as => :mission
  get 'About', :to => 'pages#about', :as => :about
  get 'Privacy', :to => 'pages#privacy', :as => :privacy
  get 'Terms', :to => 'pages#terms', :as => :terms

  get 'pros/profile'

  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/views/shared/_footer.html.erb
<footer>
<div class="container">
<div class="row">

<div class="col-sm-4 col-md-4">
<h3>Learn More</h3>
<ul>
<li><%= link_to "Our Mission", mission_path %></li> 
<li><%= link_to "About us", about_path %></li>   
</ul>
</div>

<div class="col-sm-4 col-md-4">
<h3>Explore</h3>
<ul>
<li><%= link_to "For Experts", info_path %></li> 
<li><%= link_to "Contact us", new_contact_path %></li> 
</ul>
</div>

<div class="col-sm-4 col-md-4">
<h3>Connect</h3>
<br>
<a href="https://www.facebook.com/goodlooks.me/?" class="fa fa-facebook"></a>  <a href="https://twitter.com/goodlooks_me" class="fa fa-twitter"></a> <a href="https://www.instagram.com/goodlooks/" class="fa fa-instagram"></a> <a href="https://www.linkedin.com/company/goodlooks" class="fa fa-linkedin"></a>
</div>

</div>
</div>

<div class="copy">Copyright &copy; GoodLooks, LLC, All Right Reserved
<ul>

<%= link_to "Terms of Service  |  ", terms_path %>
<%= link_to "Privacy Policy", privacy_path %> 

</ul>
</div> 
</footer>


app/views/shared/_navbar.html.erb

<header class="navbar navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, {:class=>"navbar-brand"} do %>
                      <image src="https://s3-us-west-1.amazonaws.com/goodlooks/logo.png", alt="GoodLooks Logo" >
                      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav list-unstyled list-inline navbar-right">
        
                          <% if user_signed_in? %>
                          <li class="visible-lg visible-md hidden-sm hidden-xs">
                        <!-- User button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle btn-loggedin" data-toggle="dropdown" aria-haspopup="true">
                                <b><%= current_user.name %></b>
                            </button>
                          

                            <ul class="dropdown-menu">
                                <% if current_user.level == 2 %>

                                <li><%= link_to "Profile", pro_path(current_user.pro.id)
                                 %></li>
                                <% end %>
                                <li><%= link_to "Account", edit_user_registration_path %></li>                                
                                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                            </ul>
                            </div>
                            </li>

                            <% if current_user.level == 2 %>
                            <li class="hidden-lg hidden-md visible-sm visible-xs loggedin">
                              <%= link_to "Profile", pro_path(current_user.pro.id)
                                 %>
                            </li>
                            <li class="hidden-lg hidden-md visible-sm visible-xs loggedin">
                              <%= link_to "Account", edit_user_registration_path %>
                            </li>
                            <li class="hidden-lg hidden-md visible-sm visible-xs loggedin">
                              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                            </li>

                            <% end %>
                            
                            <% else %>

                    <li>
                        <div class="btn-group">                            
                       <%= link_to new_user_registration_path, "data-no-turbolink" => true, class: 'f_bold btn btn-default btn-nav-sign btn-lg' do %>
                          Expert Sign Up
                        <% end %>    
                        </div>
                    </li>

                    <li>
                        <div class="btn-group">      
                          <%= link_to info_path, "data-no-turbolink" => true, class: 'f_bold btn btn-default btn-theme btn-lg' do %>
                          Info for Experts
                          <% end %>                                
                        </div>
                    </li>


                            <% end %>    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</header>