config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :elists

  resources :contacts

  resources :pros do
      resources :services, :photos
  end

  get 'pages/home'

  get 'InfoForExperts', :to => 'pages#info', :as => :info
  get 'Mission', :to => 'pages#mission', :as => :mission
  get 'About', :to => 'pages#about', :as => :about
  get 'Privacy', :to => 'pages#privacy', :as => :privacy
  get 'Terms', :to => 'pages#terms', :as => :terms

  get 'pros/profile'

  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates  :name, :email, :message, presence: true

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contacts = Contact.all
    respond_with(@contacts)
  end

  def show
    respond_with(@contact)
  end

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
      respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, alert: 'Thank you for your message. Someone will be in touch soon.' }
        format.json { render :show, status: :created, location: @contact}
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @contact.update(contact_params)
    respond_with(@contact)
  end

  def destroy
    @contact.destroy
    respond_with(@contact)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="col-sm-6 col-md-4 col-md-offset-1">
<%= simple_form_for(@contact, :class => "form-control") do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Your name*", label: '&nbsp;'.html_safe %>
    <%= f.input :email, placeholder: "Your email address*", label: '&nbsp;'.html_safe  %>
    <%= f.input :message, placeholder: "Your message*", label: '&nbsp;'.html_safe  %>
  </div>

	<br>
	<div class="form-actions">
    	<%= f.submit "Submit", class: 'f_bold btn btn-default btn-theme btn-lg' %>
    </div>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<section class="upcoming-evets">
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="base-container">
              <div class="section-title">
                <ul class="list-inline">
                  <li class="base-title">Contact Us</li>
                </ul>
              </div> 


<div class="row">   
	<div class="col-sm-6 col-md-4">
		<br>		
		<p>If you are a professional and interested in learning more about GoodLooks, please read more <%= link_to "here.", info_path %></p>
		<br>
		<p>Read more about GoodLooks and the management team <%= link_to "here.", about_path %></p>
		<br>
		<p>Press inquiries, business partnerships, or other requests, please complete this form to contact us.  </p>
	</div>


<%= render 'form' %>

</div>


</div>
</div>
</div>
</div>
</section>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>