config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :elists

  resources :contacts

  resources :pros do
      resources :services, :photos
  end

  get 'pages/home'

  get 'InfoForExperts', :to => 'pages#info', :as => :info
  get 'Mission', :to => 'pages#mission', :as => :mission
  get 'About', :to => 'pages#about', :as => :about
  get 'Privacy', :to => 'pages#privacy', :as => :privacy
  get 'Terms', :to => 'pages#terms', :as => :terms

  get 'pros/profile'

  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/pro.rb
class Pro < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "200x200>" }, :url =>':s3_domain_url',
  :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates  :last_name, presence: true
  
  belongs_to :user

  has_many :services, dependent: :destroy   
  accepts_nested_attributes_for :services, reject_if: :all_blank, allow_destroy: true 

  has_many :photos, dependent: :destroy   
  accepts_nested_attributes_for :photos
  
    
end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
  before_action :set_pro, only: [:show, :edit, :update, :destroy, :profile]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]


  respond_to :html 

  def index
    @pros = Pro.all
    respond_with(@pros)
  end

  def show

   @services = Service.where(pro_id: @pro.id).order("created_at DESC")

   @photos = Photo.where(pro_id: @pro.id).order("created_at DESC")
   end

  def new
    @pro = Pro.new
    @pro.user_id = current_user.id
    @pro.services.build
    @pro.photos.build

  end

  def edit
    @pro.services.build
  end

  def profile
  #  @services = Service.where(pro_id: @pro.id).order("created_at DESC")
  
   # @services = Service.where("pro_id = '#{@pro_id}'")

  end

  def create
    @pro = Pro.new(pro_params)
    @pro.user_id = current_user.id
    respond_to do |format|
      if @pro.save
        format.html { redirect_to pro_path(current_user.pro.id), notice: 'Your information has been saved.' }
        format.json { render :show, status: :created, location: @pro }
      else
        format.html { render :new }
        format.json { render json: @pro.errors, status: :unprocessable_entity }    
      end
      end 
  end

  def update
    Aws.use_bundled_cert!
    @pro.update(pro_params)
        respond_to do |format|
      if @pro.save
        if pro_params[:review] == "1"
          flash[:updated] = "Submitted for approval!"
        else
          flash[:updated] = "Profile Updated"
        end
        format.html { redirect_to pro_path(current_user.pro.id) }
        format.json { render :show, status: :created, location: @pro }
      else
        format.html { render :new }
        format.json { render json: @pro.errors, status: :unprocessable_entity }    
      end
      end 
 end 

  def destroy
    @pro.destroy
    respond_with(@pro)
  end

  private
    def set_pro
      @pro = Pro.find(params[:id])
    end


    def pro_params
      params.require(:pro).permit(:image, :name, :user_id, :last_name, :description, 
        :year_started, :city, :location, :gender, :certifications, :specialty, :hometown, 
        :quote, :author, :tip, :facebook_page, :twitter_handle, :instagram_handle, 
        :pinterest_handle, :pinterest_link, :linkedin_page, :paypal_email, :phone, 
        :alt_email, :loc_inperson_private, :loc_inperson_public, :loc_inperson_yourspace, 
        :loc_virtual_short, :loc_virtual_long, :pre_work, :cancellation,  :everyday, :execs, 
        :celebs, :bridal, :prenatal, :petites, :plus_size, :travelers, :men, :women, :lgbt, 
        :age_und20, :age_20_30, :age_30_40, :age_40_50, :age_50_60, :age_60over , :closet, 
        :personal_styling, :personal_shopping, :commercial, :bundle_offers, :stylist_other, 
        :weight_loss, :weight_gain, :firming, :bootcamp, :bodybuilding, :endurance, 
        :trainer_prenatal, :recovery, :nutrition_planning, :yoga, :pilates, :trainer_bundle, 
        :trainer_other, :nutrition_analysis, :meal_planning, :food_sensitivity, :grocery, :pantry, 
        :supplement, :body_comp, :nutritionist_bundle, :nutritionist_other, :transition, :interview, 
        :exec_coaching, :lifestyle_coaching, :public_speaking, :dating, :time_mgmt, :ADD_coaching, 
        :stress_mgmt, :parenting, :spirituality, :coach_bundle, :coach_other, :q_enjoy, :q_approach, :q_common, :review,
        service_attributes: [:title, :description, :length, :price, :pro_id],
        photo_attributes: [:image, :title])
    end
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/views/pros/_approval.html.erb

            <%= simple_form_for(@pro, :class => "form-control") do |f| %>
            <%= f.error_notification %>

  
    <%= f.input :review, :as => :boolean , label: "Check here when you're ready to have the GoodLooks team review your profile.  If you want to come back to finish the questions, leave this button unchecked." %>           
<br>    
  <div class="form-actions">
    <%= f.submit "Submit for approval", class: 'f_bold btn btn-default btn-theme btn-lg black' %>
    </div>
                

<% end %>
</div>
</div>

app/views/pros/_services_fields.html.erb
<div class ="row">
<div class="col-md-4">
  <div class="nested-fields">
    <%= f.input :title, placeholder: "Name of the service offered", label: "Service Name" %>
    <%= f.input :description, placeholder: "Provide a description of the service"  %>
    <%= f.input :length, placeholder: "Amount of time for this package in minutes"  %>
    <%= f.input :price, placeholder: "What is the price" %>
    
  </div>
  </div>
    </div>

app/views/pros/edit.html.erb
<section class="tab_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            	<div class ="center">
<br>
<h3><%= current_user.name %>, edit your profile information here</h3>
<h3>Be sure to save your work before leaving</h3>
<br>	
</div>
<%= render 'form' %>

<br>
      <% if current_user.level == 2 %>
        <%= link_to "Back to Profile Summary", pro_path(current_user.pro.id) %><br>
      <% end %>
      <br>


</div>
</div>

</div>
</section>

app/views/pros/index.html.erb
<h1>Listing pros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pros.each do |pro| %>
      <tr>
        <td><%= pro.name %></td>
        <td><%= pro.user_id %></td>
        <td><%= pro.user %></td>
        <td><%= link_to 'Show', pro %></td>
        <td><%= link_to 'Edit', edit_pro_path(pro) %></td>
        <td><%= link_to 'Destroy', pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pro', new_pro_path %>

app/views/pros/new.html.erb
<section class="tab_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
<h5>
	<b>Please get started building your profile.  You can come back anytime to finish - just be sure to save your profile first.</b>
<br><br>	
	We started GoodLooks with the belief that every person should feel comfortable in their own skin.  Our goal is to create a destination for successful men and women to find the right professional to help them look their best, feel their best, and be their best. 
<br><br>
First we need you tell us a bit about yorurself and your business.  This allows users to better search and find you.  Next, we'll ask you to add the services you provide.
<br><br>
</h5>


<%= render 'form' %>


</div>
</div>

</div>
</section>

app/views/pros/profile.html.erb

                                      <option selected value="Select a service">Select a service</option>
                                      <% @services.each do |service| %>
                                          <p>Service: <%= service.title %></p>
                                      <% end %>

app/views/pros/show.html.erb
<section class="tab_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

				<div class="base-container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="section-title">

                  <%if flash[:updated] %>
                    <div class="alert alert-success"><%= flash[:updated] %></div>
                  <%end%>

                                <ul class="list-inline">
									<li class="base-title"><%= current_user.name %>'s profile </li>
                                </ul>
                            </div>

                        </div>
                    </div>		

                    <div class="col-sm-12 center">
                        <h2>3 steps to building your profile</h2>
                        <br>

                    </div>


                    <div class="row">                    
                    <div class="col-sm-10">
                                <h3>1. Share your expertise</h3>
                            <p>Add your information.  A complete a profile helps users better find you.</p>                            
                            <%= link_to edit_pro_path(current_user.pro.id), "data-no-turbolink" => true, class: 'f_bold btn btn-default btn-theme btn-lg' do %>
                            Edit Your Info
                            <% end %> 

                            <br><br>
                        </div>
                    </div>

                    <div class="row">    
                        <div class="col-sm-10">

							<h3>2.  Add the services you offer</h3>
                            <p>Your current services offered:</p>
                            <% if @pro.services.count > 0 %>

								<% @services.each do |service| %>
    								<p><b>Service: <%= service.title %></p></b>
    								<p>Description: <%= service.description %></p>
    								<p>Length: <%= service.length %> mins</p>
    								<p>Price: <%= number_to_currency(service.price) %></p>      
    								<p><%= link_to 'Edit  |  ', edit_pro_service_path(current_user.pro.id, service) %>
                                    <%= link_to 'Delete', pro_service_path(current_user.pro.id, service), method: :delete, data: { confirm: 'Are you sure?' }
                                    %> </p>
    								<br>
								<% end %>
                                <% else %>
                                <p> No services listed yet </p>
                                <% end %>
                                <%= link_to new_pro_service_path(current_user.pro.id), "data-no-turbolink" => true, class: 'f_bold btn btn-default btn-theme btn-lg' do %>
                                Add A Service
                                <% end %> 


                                <br> <br>                           
                        </div>
                    </div>


                    <div class="row">    
                        <div class="col-sm-10">
							<h3>3. Add portfolio photos</h3>
								<p>Add pictures of you and/or your work to give your clients a better understanding of your approach</p><br>	
								<% @photos.each do |photo| %>
                                    <p><%= photo.title %></p>
    								<p><%= image_tag(photo.image.url(:thumb)) %></p>
                    <p><%= link_to 'Edit  |  ', edit_pro_photo_path(current_user.pro.id, photo) %>
                    <%= link_to 'Delete', pro_photo_path(current_user.pro.id, photo), method: :delete, data: { confirm: 'Are you sure?' }
                    %></p>                    
                    <br>
								<% end %>

                                <%= link_to new_pro_photo_path(current_user.pro.id), "data-no-turbolink" => true, class: 'f_bold btn btn-default btn-theme btn-lg' do %>
                                Add A Photo
                                <% end %> 


                                <br>                            
                        </div>
                    </div>


						<div class="row" style="padding: 5% 0%">
                        	<div class="col-sm-10 col-md-offset-1">
                                <h3>Once you submit all your information to GoodLooks we will work with you to launch your complete profile page shortly!  </h3>
                                 <%= render :partial => '/pros/approval' %>
                        
							</div>
						</div>
</div>
</div>
</div>
</div>
</div>
</section>